CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login_username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    rights TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_accounts_login_username_lower ON accounts ((lower(login_username)));

CREATE TABLE IF NOT EXISTS account_login_aliases (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    login_username TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_account_login_aliases_lower ON account_login_aliases ((lower(login_username)));

CREATE INDEX IF NOT EXISTS idx_account_login_aliases_account ON account_login_aliases (account_id);
