-- Display names keep original casing in storage; uniqueness is case-insensitive.

ALTER TABLE account_characters
    DROP CONSTRAINT IF EXISTS account_characters_display_name_key;

CREATE UNIQUE INDEX IF NOT EXISTS uq_account_characters_display_name_lower
    ON account_characters (lower(trim(display_name)))
    WHERE display_name IS NOT NULL AND btrim(display_name) <> '';

-- Held names after a rename: store prior casing, block reclaim case-insensitively.
ALTER TABLE display_name_holds
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE display_name_holds
    DROP CONSTRAINT IF EXISTS display_name_holds_pkey;

ALTER TABLE display_name_holds
    ADD CONSTRAINT display_name_holds_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_display_name_holds_held_name_lower
    ON display_name_holds (lower(trim(held_name)))
    WHERE btrim(held_name) <> '';
